'''

Author: Jake Bradford

'''
import os
import json
import operator
from functools import reduce
from collections import deque

from . import config

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
sns.set_theme(style="white", rc={"axes.facecolor": (0, 0, 0, 0)})

from .data import get_assembly_cache

from ete3.ncbi_taxonomy.ncbiquery import NCBITaxa
from ete3.parser.newick import read_newick, write_newick
from plot_eteTree import *

def add_assembly_info_to_dataframe(dfIn, colAccession='accession', fieldsToAdd=['organismName', 'strain', 'taxId', 'assemblyInfo/assemblyLevel', 'assemblyInfo/assemblyName']):
    '''Given some DataFrame with column `colAccession`, add additional columns from the data report
    generated by NCBI.
    
    The schema is available here:
        https://www.ncbi.nlm.nih.gov/datasets/docs/v1/reference-docs/data-reports/genome-assembly/#ncbi-datasets-v1-reports-AssemblyDataReport
    
    Arguments:
        dfIn (DataFrame):      The DataFrame to add columns to
        colAccession (string): The name of the column containing NCBI accessions
        fieldsToAdd (list):    Fields from the data report (NCBI data_report.json) to add. 
                               To add items that are nested, separate each level using a forward-
                               slash. For example, `assemblyInfo/assemblyLevel`.

    Returns:
        The updated DataFrame (also edits in-place).
    '''
    
    # Load data reports for the accessions in the dataframe
    data_reports = {}   
    
    for accs in set(dfIn[colAccession]):
        fpReport = os.path.join(get_assembly_cache(accs), 'data_report.json')
        if os.path.exists(fpReport):
            with open(fpReport, 'r') as fp:
                data_reports[accs] = json.loads(fp.readline())

    # For those assemblies where we have a data report, add the requested columns to the dataframe
    for accs in data_reports:
        for fieldToAdd in fieldsToAdd:
        
            # inspiration from https://stackoverflow.com/a/14692747/12891825
            try:
                val = reduce(operator.getitem, fieldToAdd.split('/'), data_reports[accs])        
            except Exception as e:
                val = None
        
            dfIn.loc[dfIn[colAccession] == accs, fieldToAdd] = val
    
    return dfIn

def generate_df_of_species_data_from_accessions(accessions, common_nodes=False):
    '''This function generates a DataFrame of the data needed to visualise the
    phylogenetic tree in a web browser.
    
    The columns of the DataFrame are:
        1. taxId
        2. commonName
        3. species
        4. taxonomy
    
    Arguments:
        accessions (list):  The accessions for which tax IDs are identified from
        common_nodes (bool): Also get the data for ancestory nodes of the tree
        
    Returns:
        A DataFrame intended to be written as CSV
    '''
    
    df = pd.DataFrame({'number' : accessions})
    
    add_assembly_info_to_dataframe(df, 
        colAccession='number', 
        fieldsToAdd=['taxId', 'commonName', 'organismName']
    )
    
    df = df.astype({'taxId' : 'int32'})
    
    df['commonName'].fillna(df['organismName'], inplace=True)
    
    df['taxonomy'] = 'TODO'
    
    del df['number']
    
    return df

def generate_df_of_species_data_from_tax_ids(tax_ids):
    '''This function generates a DataFrame of the data needed to visualise the
    phylogenetic tree in a web browser.
    
    The columns of the DataFrame are:
        1. taxId
        2. commonName
        3. species
        4. taxonomy
    
    Arguments:
        accessions (list):  The accessions for which tax IDs are identified from
        
    Returns:
        A DataFrame intended to be written as CSV
    '''
    
    ncbi = NCBITaxa()
    tree = ncbi.get_topology(tax_ids)
    
    tax2name, tax2track, tax2rank = ncbi.annotate_tree(tree)

    df = pd.DataFrame([tax2name, tax2track, tax2rank]).T
    df.columns = ['commonName', 'taxonomy', 'species']
    df['taxonomy'] = 'TODO' # currently provides: [1, 10239, 687329, 227307, 12618, 73476]
    df['species'] = df['commonName'] # currently provides: [1, 10239, 687329, 227307, 12618, 73476]
    df['taxId'] = df.index
    return df[['taxId', 'commonName', 'species', 'taxonomy']]
        

def get_tax_ids_from_accessions(accessions, uniq=True):
    '''Given a list of accessions, return a list of taxonomy IDs.
    
    Arguments:
        accessions (list): A list of accessions
        uniq (bool):        If true, a set of tax IDs will be returned. Else, 
            duplicate tax IDs may be returned.
    
    Returns:
        A list or set of tax IDs (see arg `uniq`).
    '''
    tax_ids = []
    for accs in set(accessions):
        fpReport = os.path.join(get_assembly_cache(accs), 'data_report.json')
        if os.path.exists(fpReport):
            with open(fpReport, 'r') as fp:
                report = json.loads(fp.readline())
            if 'taxId' in report:
                tax_ids.append(report['taxId'])
            else:
                if config.VERBOSE:
                    print(f'Could not find taxId of {accs}')
    
    return tax_ids if not uniq else list(set(tax_ids))

def get_descendant_tax_ids_from_root_tax_id(root_tax_id=None, max_depth=None):
    '''Given some taxonomy ID, find the taxonomy IDs of descendant nodes
    
    Arguments:
        root_tax_id (int): The root tax_id. Optional. default is config.ROOT_TAX_ID
        
    Returns:
        A list of tax IDS
        
    '''
    if root_tax_id is None:
        root_tax_id = config.ROOT_TAX_ID
    
    ncbi = NCBITaxa()
    tree = ncbi.get_topology([root_tax_id])

    tree.depth = 0

    ids = []
    
    tovisit = deque([tree])
    while len(tovisit)>0:
        node = tovisit.popleft()
        if max_depth is None or node.depth < max_depth:
            ids.append(int(node.name))
            
        if len(node.children) > 0:
            for child in node.children:
                child.depth = node.depth + 1
            tovisit.extend(node.children)
    
    return ids

def get_tax_ranks_in_order(root_node=10239):
    '''Not finished.
    
    This method should be used sparingly. Once the result has been computed
    once, it should be cached. The taxonomy rank nomeclature used by NCBI is not 
    explicit (or, at least, I can't find any documentation). This function
    uses the Viruses superkingdom node of the tree to find ranks, in order from
    superkingdom to species.
    
    Returns:
        A list of rank names where the index value indicates is level in the tree
    '''
    ranks = []
    
    ncbi = NCBITaxa()
    
    tax_ids = get_descendant_tax_ids_from_root_tax_id(tax_id=root_node)

    tree = ncbi.get_topology(tax_ids)

    tax2name, tax2track, tax2rank = ncbi.annotate_tree(tree)

    tax2depth = {}
    
    tree.depth = 0

    tovisit = deque([tree])
    while len(tovisit)>0:
        node = tovisit.popleft()
        if len(node.children) > 0:
            for child in node.children:
                child.depth = node.depth + 1
                tax2depth[int(child.name)] = node.depth + 1
            tovisit.extend(node.children)

    
    print(tax2rank)
    return tax2depth, tax2rank

    
    

def filter_tax_ids_by_level():
    return None
  
def generate_newick_string_from_tax_ids(tax_ids):
    '''This function generates Newick string of the data needed to visualise the
    phylogenetic tree in a web browser. See https://en.wikipedia.org/wiki/Newick_format
    
    Arguments:
        tax_ids (list):  The taxonomy IDs to include in the tree
        
    Returns:
        A Newick string
    '''
    
    ncbi = NCBITaxa()

    return write_newick(
        ncbi.get_topology(
            tax_ids
        )
    )
    
def generate_newick_string_from_accessions(accessions, rank_limit=None):
    '''This function generates Newick string of the data needed to visualise the
    phylogenetic tree in a web browser. See https://en.wikipedia.org/wiki/Newick_format
    
    Arguments:
        accessions (list):  The accessions for which tax IDs are identified from
        
    Returns:
        A Newick string
    '''
    
    ncbi = NCBITaxa()

    return write_newick(
        ncbi.get_topology(
            get_tax_ids_from_accessions(
                accessions
            ),
            rank_limit=rank_limit
        )
    )    

def generate_df_phylo_node_scores_from_tax_ids(tax_ids):
    '''Given a list of accessions and scores, calculate node scores.
    
    Arguments:
        tax_ids (list): A list of taxonomy IDs
        
    Returns:
        A DataFrame with columns: tax_id, score
    
    '''
    with open('/home/jake/ViralCut/43740568-scores.csv', 'r') as fp:
        df = pd.read_csv(fp)
    
    df['local'] = 10000.0 / df['mit'] - 100.0

    ncbi = NCBITaxa()
    tree = ncbi.get_topology(tax_ids)#, intermediate_nodes=True)

    data = {'tax_id': [], 'score' : []}

    for idx, i in enumerate(tree.traverse(strategy="levelorder")):
        species = map(float, i.get_leaf_names())
        df_species = df[df['taxId'].isin(species)]
        mit = 10000.0 / (100.0 + df_species['local'].sum())
        
        data['tax_id'].append(i.name)
        data['score'].append(mit)
    
    return pd.DataFrame(data)

def generate_df_phylo_node_scores_from_accessions(accessions):
    '''Given a list of accessions and scores, calculate node scores.
    
    Arguments:
        accessions (list): A list of accessions
        
    Returns:
        A DataFrame with columns: tax_id, score
    
    '''
    tax_ids = get_tax_ids_from_accessions(accessions)
    return generate_df_phylo_node_scores_from_tax_ids(tax_ids)

def prepare_files_for_visualisation(accessions, file_prefix):
    '''The web-based visualisation needs three files, this function generates
    each using other methods within this module. 
    
    Arguments:
        accessions (list):      A list of accessions to include. Note, 
            these are used only to lookup which taxonomy IDs should be included 
            in the tree.
        file_prefix (string):   A file path prefix to write to. If a directory
            is specified then the files will be named `species.csv`, 
            `newick.txt` and `scores.csv`. If not a directory then the names 
            follow this convention: f'{file_prefix}.species.csv'.
    '''
    
    # Make sure the prefix ends with a `.` but only if it is not a directory
    if not os.path.isdir(file_prefix):
        if file_prefix.endswith('.'):
            file_prefix = file_prefix[:-1]
    
        fp_species_data = f'{file_prefix}.species.csv'
        fp_newick_string = f'{file_prefix}.newick.txt'
        fp_node_scores = f'{file_prefix}.scores.csv'
    else:
        fp_species_data = os.path.join(file_prefix, 'species.csv')
        fp_newick_string = os.path.join(file_prefix, 'newick.txt')
        fp_node_scores = os.path.join(file_prefix, 'scores.csv')
        
    with open(fp_species_data, 'w') as fp:
        df = generate_df_of_species_data_from_accessions(accessions)
        df.to_csv(fp, index=False)
        
    with open(fp_newick_string, 'w') as fp:
        newick = generate_newick_string_from_accessions(accessions)
        fp.write(f'{newick}\n')
        
    with open(fp_node_scores, 'w') as fp:
        df = generate_df_phylo_node_scores_from_accessions(accessions)
        df.to_csv(fp, index=False)

    if config.VERBOSE:
        print((
            f'Wrote to:\n'
            f'\t{fp_species_data}\n'
            f'\t{fp_newick_string}\n'
            f'\t{fp_node_scores}'
        ))

def get_children(tree):
    return tree.children

def generate_phylogenetic_tree_from_tax_ids(tax_ids):
    with open('43740568-scores.csv', 'r') as fp:
        df = pd.read_csv(fp)
    
    df['local'] = 10000.0 / df['mit'] - 100.0
    #print(df)
    
    ncbi = NCBITaxa()
    tree = ncbi.get_topology(tax_ids)#, intermediate_nodes=True)
    tax2name, tax2track, tax2rank = ncbi.annotate_tree(tree)
    
    for idx, i in enumerate(tree.traverse(strategy="levelorder")):
        species = map(float, i.get_leaf_names())
        df_species = df[df['taxId'].isin(species)]
        mit = 10000.0 / (100.0 + df_species['local'].sum())
        i.mit = f"mit: {round(mit, 3)}"
        i.detailed_name = f"{tax2name[int(i.name)]} ({tax2rank[int(i.name)]})"
        
        if False:
            print(f"{i.name} {tax2name[int(i.name)]} ({tax2rank[int(i.name)]}) ({len(i.children)} children) ({len(i.get_leaf_names())} leaves): ")
            for x in i.children[0:5]:
                print(f"    {x.name} ({tax2rank[int(x.name)]}): {tax2name[int(x.name)]}")

            print(f"    mit score: {mit} (on {len(df_species)} observations)")
            print('\n')

            if idx == 8:
                break
    print(write_newick(ncbi.get_topology(ncbi.get_descendant_taxa(10240))))
    #print(tree.get_ascii(attributes=['name', 'detailed_name', 'mit']))

    
    
    #nstyle = NodeStyle()
    #nstyle['fgcolor'] = 'red'
    #nstyle['hz_line_color'] = 'grey'
    #nstyle['hz_line_type'] = 0
    #nstyle['hz_line_width'] = 0
    #
    #nstyle2 = NodeStyle()
    #nstyle2['size'] = 8
    #nstyle2['shape'] = 'square'
    #nstyle2['fgcolor'] = 'green'
    #nstyle2['hz_line_color'] = 'orange'
    #nstyle2['hz_line_type'] = 1
    #nstyle2['vt_line_color'] = 'blue'
    #nstyle2['vt_line_width'] = 2
    #nstyle2['vt_line_type'] = 2
    #
    #for n in tree.iter_descendants():
    #    if n.is_leaf():
    #        n.set_style(nstyle)
    #    else:
    #        n.set_style(nstyle2)
    #tree.set_style(nstyle2)
    ######################################
    ### plot with matplotlib
    #fig, ax = plt.subplots(figsize=(25,50))
    #axe, coords = plot_tree(tree, axe=ax, attributes=['name', 'detailed_name', 'mit'])
    #fig.savefig('axe.png')   # save the figure to file

    


# def plot_scores_ridge()
#     # Create the data
#     rs = np.random.RandomState(1979)
#     x = rs.randn(500)
#     g = np.tile(list("ABCDEFGHIJ"), 50)
#     df = pd.DataFrame(dict(x=x, g=g))
#     m = df.g.map(ord)
#     df["x"] += m
# 
#     # Initialize the FacetGrid object
#     pal = sns.cubehelix_palette(10, rot=-.25, light=.7)
#     g = sns.FacetGrid(df, row="g", hue="g", aspect=15, height=.5, palette=pal)
# 
#     # Draw the densities in a few steps
#     g.map(sns.kdeplot, "x",
#           bw_adjust=.5, clip_on=False,
#           fill=True, alpha=1, linewidth=1.5)
#     g.map(sns.kdeplot, "x", clip_on=False, color="w", lw=2, bw_adjust=.5)
# 
#     # passing color=None to refline() uses the hue mapping
#     g.refline(y=0, linewidth=2, linestyle="-", color=None, clip_on=False)
# 
# 
#     # Define and use a simple function to label the plot in axes coordinates
#     def label(x, color, label):
#         ax = plt.gca()
#         ax.text(0, .2, label, fontweight="bold", color=color,
#                 ha="left", va="center", transform=ax.transAxes)
# 
# 
#     g.map(label, "x")
# 
#     # Set the subplots to overlap
#     g.figure.subplots_adjust(hspace=-.25)
# 
#     # Remove axes details that don't play well with overlap
#     g.set_titles("")
#     g.set(yticks=[], ylabel="")
#     g.despine(bottom=True, left=True)